src/SFA.DAS.Courses.Data.UnitTests/Customisations/StandardsAreLarsValidAttribute.cs
src/SFA.DAS.Courses.Data.UnitTests/Customisations/StandardsNotLarsValidAttribute.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingCount.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingFilteredStandards.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingStandards.cs

adding autofixture customisations and updating tests to use them.

Add autofixture customisations

---

src/SFA.DAS.Courses.Api.UnitTests/Controllers/Import/WhenCallingImport.cs
src/SFA.DAS.Courses.Api/Controllers/DataLoadController.cs
src/SFA.DAS.Courses.Application.UnitTests/CoursesImport/Handlers/WhenHandlingImportDataCommand.cs
src/SFA.DAS.Courses.Application/CoursesImport/Handlers/ImportStandards/ImportDataCommandHandler.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/FrameworksImportService.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/LarsImportService.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
src/SFA.DAS.Courses.Data.UnitTests/Search/WhenBuildingACoursesIndex.cs
src/SFA.DAS.Courses.Data/Search/CoursesIndexBuilder.cs

IIndexBuilder interface brought into ImportDataCommandHandler & test updated

FAT2-131 - refresh lucene on import

---

azure/template.json

Renamed arm template parameter to backendAccessRestrictions
Directly match with variable group variable name

Renamed arm template parameter to backendAccessRestrictions

---

src/SFA.DAS.Courses.Application.UnitTests/CoursesImport/Services/WhenImportingStandards.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs

Fixed issue with duplicate LARS codes

FAT2-256 Data load bug

---

src/SFA.DAS.Courses.Domain/Courses/LevelsConstant.cs

FAT2-216 - Rename_Course_Levels

---

src/SFA.DAS.Courses.Api/ApiResponses/GetStandardResponse.cs
src/SFA.DAS.Courses.Data/Configuration/Standard.cs
src/SFA.DAS.Courses.Data/Configuration/StandardImport.cs
src/SFA.DAS.Courses.Data/Extensions/ValueConversionExtensions.cs
src/SFA.DAS.Courses.Data/Repository/StandardRepository.cs
src/SFA.DAS.Courses.Database/Tables/Standard.sql
src/SFA.DAS.Courses.Database/Tables/Standard_Import.sql
src/SFA.DAS.Courses.Domain.UnitTests/Entities/WhenCastingFromStandardApiTypeToStandardImport.cs
src/SFA.DAS.Courses.Domain/Courses/Standard.cs
src/SFA.DAS.Courses.Domain/Entities/Standard.cs
src/SFA.DAS.Courses.Domain/Entities/StandardBase.cs
src/SFA.DAS.Courses.Domain/Entities/StandardImport.cs
src/SFA.DAS.Courses.Domain/ImportTypes/Standard.cs

Provide them via arrays of strings:
```
{
"id": 470,
"title": "Interior systems installer",
"skills": [
"Measure and set out from drawings provided...",
"Select the appropriate materials, tools an...",
...
"Remove sections of ceiling and replace dam..."
],
"knowledge": [
"General principles of building design and ...",
"The different methods to install dry linin...",
...
"The importance of setting out and suspensi..."
],
"behaviours": [
"Safety first approach",
"An attention to detail",
...
"Working towards high quality of all work c..."
],
}
```

Expose Skills, Knowledge and Behaviours via Standards API

---

src/SFA.DAS.Courses.Application.UnitTests/CoursesImport/Services/WhenImportingStandards.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs

Import all standards from ifate, only storing the latest version.

FAT2-321 - Remove status filter on import

---

src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/WhenCallingGetStandardsList.cs
src/SFA.DAS.Courses.Api/Controllers/StandardsController.cs
src/SFA.DAS.Courses.Api/DataFiles/frameworks_2.0.json
src/SFA.DAS.Courses.Api/SFA.DAS.Courses.Api.csproj
src/SFA.DAS.Courses.Application.UnitTests/Courses/Queries/WhenGettingStandardsList.cs
src/SFA.DAS.Courses.Application.UnitTests/Courses/Services/WhenGettingStandardsCount.cs
src/SFA.DAS.Courses.Application.UnitTests/Courses/Services/WhenGettingStandardsList.cs
src/SFA.DAS.Courses.Application/Courses/Queries/GetStandardsList/GetStandardsListQuery.cs
src/SFA.DAS.Courses.Application/Courses/Queries/GetStandardsList/GetStandardsListQueryHandler.cs
src/SFA.DAS.Courses.Application/Courses/Services/StandardsService.cs
src/SFA.DAS.Courses.Data.UnitTests/Extensions/WhenFilteringAvailableStandards.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingCount.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingFilteredStandards.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingStandards.cs
src/SFA.DAS.Courses.Data/Extensions/StandardAvailabilityExtension.cs
src/SFA.DAS.Courses.Data/Repository/StandardRepository.cs
src/SFA.DAS.Courses.Domain/Interfaces/IStandardRepository.cs
src/SFA.DAS.Courses.Domain/Interfaces/IStandardsService.cs
src/SFA.DAS.Courses.Infrastructure/FileHelper/JsonFileHelper.cs

Add param, defaulting to true to filter only available to start standards.

FAT2-263 all standards

---

src/SFA.DAS.Courses.Api.AcceptanceTests/Steps/StandardsSteps.cs

This is just adding a test for a fix made earlier

SV-443 count test

---

IntegrationTests/Courses API Tests.postman_collection.json
IntegrationTests/CoursesApiTests.postman_environment.json

New pull request based off master

SV-482 Add integration tests

---

src/SFA.DAS.Courses.Api/ApiResponses/GetStandardDetailResponse.cs
src/SFA.DAS.Courses.Api/ApiResponses/GetStandardResponse.cs
src/SFA.DAS.Courses.Domain/Courses/Standard.cs

I have removed the CoreSkillsCount field as it is not being used

SV-528 delete core skill count field

---

src/SFA.DAS.Courses.Api/ApiResponses/GetStandardDetailResponse.cs
src/SFA.DAS.Courses.Api/ApiResponses/GetStandardResponse.cs
src/SFA.DAS.Courses.Data/Configuration/LarsStandard.cs
src/SFA.DAS.Courses.Data/Configuration/LarsStandardImport.cs
src/SFA.DAS.Courses.Database/Tables/LarsStandard.sql
src/SFA.DAS.Courses.Database/Tables/LarsStandard_Import.sql
src/SFA.DAS.Courses.Domain.UnitTests/Courses/WhenCastingToStandardDatesFromEntity.cs
src/SFA.DAS.Courses.Domain.UnitTests/Courses/WhenCastingToStandardFromEntity.cs
src/SFA.DAS.Courses.Domain.UnitTests/Entities/WhenCastingFromStandardCsvToLarsStandardImport.cs
src/SFA.DAS.Courses.Domain/Courses/Standard.cs
src/SFA.DAS.Courses.Domain/Entities/LarsStandard.cs
src/SFA.DAS.Courses.Domain/Entities/LarsStandardBase.cs
src/SFA.DAS.Courses.Domain/Entities/LarsStandardImport.cs
src/SFA.DAS.Courses.Domain/ImportTypes/StandardCsv.cs

Add sector code from Lars import to the standard and standards list response.

FAT2-421 recruit v1 decom

---

src/SFA.DAS.Courses.Domain/Configuration/Constants.cs
src/SFA.DAS.Courses.Infrastructure/PageParsing/LarsPageParser.cs

Updated lars url to new version

---

src/SFA.DAS.Courses.Data.UnitTests/Extensions/WhenFilteringClosedToNewStarts.cs
src/SFA.DAS.Courses.Data/Extensions/StandardFilterExtension.cs
src/SFA.DAS.Courses.Domain/Search/StandardFilter.cs

Need get list of courses that are closed to new starts, this is used to stop any active employer demands.

AEDB-52 get list of courses closed to new starts

---

src/SFA.DAS.Courses.Api.AcceptanceTests/Steps/StandardsSteps.cs
src/SFA.DAS.Courses.Api.UnitTests/Controllers/Standards/StandardToGetStandardResponseOptions.cs
src/SFA.DAS.Courses.Api/ApiResponses/GetStandardDetailResponse.cs
src/SFA.DAS.Courses.Api/ApiResponses/GetStandardResponse.cs
src/SFA.DAS.Courses.Application.UnitTests/CoursesImport/Services/WhenImportingStandards.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
src/SFA.DAS.Courses.Database/Tables/Standard.sql
src/SFA.DAS.Courses.Database/Tables/Standard_Import.sql
src/SFA.DAS.Courses.Domain.UnitTests/Entities/WhenCastingFromStandardApiTypeToStandardImport.cs
src/SFA.DAS.Courses.Domain.UnitTests/Entities/WhenCastingFromStandardImportToStandard.cs
src/SFA.DAS.Courses.Domain/Courses/Standard.cs
src/SFA.DAS.Courses.Domain/Entities/Standard.cs
src/SFA.DAS.Courses.Domain/Entities/StandardBase.cs
src/SFA.DAS.Courses.Domain/Entities/StandardImport.cs
src/SFA.DAS.Courses.Domain/ImportTypes/Standard.cs

* Schema updates.
* EPAChanged field added to API output.
* Set EPAChanged flag based on Change text value
* Remove epaChanged field from GetStandardResponse per Chris' comments.

SV-350-StandardVersioningApply

---

src/SFA.DAS.Courses.Application.UnitTests/CoursesImport/Services/WhenImportingLarsData.cs
src/SFA.DAS.Courses.Application/CoursesImport/Services/LarsImportService.cs

The last LARS file is no longer compared against the new to see if it needs updating. It is now updated every time regardless

AEDB-121 - Remove LARS file check

---

src/SFA.DAS.Courses.Api/SFA.DAS.Courses.Api.csproj
src/SFA.DAS.Courses.Domain.UnitTests/Entities/WhenCastingFromStandardApiTypeToStandardImport.cs
src/SFA.DAS.Courses.Domain/Entities/StandardImport.cs

Added trimming to the mapping of options.

SV-1398 Update mapping to trim options

---

src/SFA.DAS.Courses.Domain/Configuration/Constants.cs

Update LarsBasePageUrl and download page url due to update from LARS

FAI-583 - Update LarsBasePageURL

---

src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingStandards.cs
src/SFA.DAS.Courses.Data.UnitTests/Repository/StandardRepository/WhenGettingStandardsByIFateReferenceNumber.cs
src/SFA.DAS.Courses.Data/Repository/StandardRepository.cs

Add projection to reduce the response size when getting all standards

FAI-801 - Add query projection for when getting all results

---

src/SFA.DAS.Courses.Application/CoursesImport/Services/StandardsImportService.cs
src/SFA.DAS.Courses.Domain/Interfaces/ISlackNotificationService.cs
src/SFA.DAS.Courses.Infrastructure.UnitTests/Api/WhenNotifiyingValidationFailuresViaSlackPost.cs
src/SFA.DAS.Courses.Infrastructure/Api/SlackNotificationService.cs

Allow either a user or a group to be specified in the notification

P2-2266 Slack configuration to allow either users or groups
